export const africanCountryCodes = [
  { code: "+213", label: "Algeria" },
  { code: "+244", label: "Angola" },
  { code: "+229", label: "Benin" },
  { code: "+267", label: "Botswana" },
  { code: "+226", label: "Burkina Faso" },
  { code: "+257", label: "Burundi" },
  { code: "+237", label: "Cameroon" },
  { code: "+238", label: "Cape Verde" },
  { code: "+236", label: "Central African Rep." },
  { code: "+235", label: "Chad" },
  { code: "+269", label: "Comoros" },
  { code: "+242", label: "Congo (Brazzaville)" },
  { code: "+243", label: "Congo (Kinshasa)" },
  { code: "+253", label: "Djibouti" },
  { code: "+20", label: "Egypt" },
  { code: "+240", label: "Equatorial Guinea" },
  { code: "+291", label: " Eritrea" },
  { code: "+251", label: "Ethiopia" },
  { code: "+241", label: "Gabon" },
  { code: "+220", label: " Gambia" },
  { code: "+233", label: " Ghana" },
  { code: "+224", label: "Guinea" },
  { code: "+245", label: "Guinea-Bissau" },
  { code: "+225", label: "Ivory Coast" },
  { code: "+254", label: "Kenya" },
  { code: "+266", label: "Lesotho" },
  { code: "+231", label: "Liberia" },
  { code: "+218", label: "Libya" },
  { code: "+261", label: "Madagascar" },
  { code: "+265", label: "Malawi" },
  { code: "+223", label: "Mali" },
  { code: "+222", label: "Mauritania" },
  { code: "+230", label: "Mauritius" },
  { code: "+212", label: "Morocco" },
  { code: "+258", label: "Mozambique" },
  { code: "+264", label: "Namibia" },
  { code: "+227", label: "Niger" },
  { code: "+234", label: "Nigeria" },
  { code: "+250", label: "Rwanda" },
  { code: "+290", label: " Saint Helena" },
  { code: "+239", label: "São Tomé & Príncipe" },
  { code: "+221", label: "Senegal" },
  { code: "+248", label: "Seychelles" },
  { code: "+232", label: "Sierra Leone" },
  { code: "+252", label: "Somalia" },
  { code: "+27", label: "South Africa" },
  { code: "+211", label: "South Sudan" },
  { code: "+249", label: "Sudan" },
  { code: "+268", label: "Eswatini" },
  { code: "+255", label: "Tanzania" },
  { code: "+228", label: "Togo" },
  { code: "+216", label: "Tunisia" },
  { code: "+256", label: "Uganda" },
  { code: "+260", label: "Zambia" },
  { code: "+263", label: "Zimbabwe" },
];
